#!/bin/bash

# Compile C source to object file
riscv64-unknown-elf-gcc \
    -march=rv32im \
    -mabi=ilp32 \
    -nostdlib \
    -ffreestanding \
    -g3 \
    -gdwarf-4 \
    -c example.c \
    -o example.o

if [ $? -ne 0 ]; then
    echo "C compilation failed"
    exit 1
fi


# Compile startup assembly
riscv64-unknown-elf-gcc \
    -march=rv32im \
    -mabi=ilp32 \
    -nostdlib \
    -ffreestanding \
    -g3 \
    -gdwarf-4 \
    -c startup.s \
    -o startup.o

if [ $? -ne 0 ]; then
    echo "startup.s compilation failed"
    exit 1
fi


# Compile quarter_round assembly
riscv64-unknown-elf-gcc \
    -march=rv32im \
    -mabi=ilp32 \
    -nostdlib \
    -ffreestanding \
    -g3 \
    -gdwarf-4 \
    -c quarter_round.s \
    -o quarter_round.o

if [ $? -ne 0 ]; then
    echo "quarter_round.s compilation failed"
    exit 1
fi


# Compile inner_block assembly
riscv64-unknown-elf-gcc \
    -march=rv32im \
    -mabi=ilp32 \
    -nostdlib \
    -ffreestanding \
    -g3 \
    -gdwarf-4 \
    -c inner_block.s \
    -o inner_block.o

if [ $? -ne 0 ]; then
    echo "inner_block.s compilation failed"
    exit 1
fi


# Compile math assembly
riscv64-unknown-elf-gcc \
    -march=rv32im \
    -mabi=ilp32 \
    -nostdlib \
    -ffreestanding \
    -g3 \
    -gdwarf-4 \
    -c math_asm.s \
    -o math_asm.o

if [ $? -ne 0 ]; then
    echo "Math assembly compilation failed"
    exit 1
fi


# Link object files together
riscv64-unknown-elf-gcc \
    -march=rv32im \
    -mabi=ilp32 \
    -nostdlib \
    -ffreestanding \
    -g3 \
    -gdwarf-4 \
    startup.o \
    example.o \
    math_asm.o \
    quarter_round.o \
    inner_block.o \
    -T linker.ld \
    -o example.elf

if [ $? -eq 0 ]; then
    echo "Build successful: example.elf created"
    echo "Object files: example.o startup.o math_asm.o quarter_round.o inner_block.o"
else
    echo "Linking failed"
    exit 1
fi