// ------------------------------------------------------------
// Brayan Alpizar ELizondo
// Arquitectura de Computadores 1
// Ingeniería en Computadores - 2026 
// ------------------------------------------------------------
// RISC-V Assembly and C Integration: ChaCha20 Stream Cipher
// This program demonstrates how to integrate RISC-V assembly code with C to implement
// the ChaCha20 stream cipher. It includes both the assembly implementation of the
// ChaCha20 block function and the C code to manage keys, nonces, and plaintext.
// ------------------------------------------------------------


// Buffer generated by the ChaCha20 block function (64-byte keystream block)
extern unsigned char cyphered_block[64];

// Define a 32-bit unsigned integer type for portability and clarity
typedef unsigned int uint32_t;

// 256-bit ChaCha20 key (8 words × 32 bits)
uint32_t key[8] = {
    0x03020100, 0x07060504, 0x0b0a0908, 0x0f0e0d0c,
    0x13121110, 0x17161514, 0x1b1a1918, 0x1f1e1d1c
};

// 96-bit nonce used by ChaCha20 (3 words × 32 bits)
// Ensures uniqueness of the keystream for each encryption
uint32_t nonce[3] = {
    0x00000000,
    0x4a000000,
    0x00000000
};

// Initial block counter used by ChaCha20
// Incremented internally to generate new keystream blocks
uint32_t counter = 1;

// Plaintext message to be encrypted
unsigned char message_1[] =
    "Any submission to the IETF intended by the Contributor for publication as all or "
    "part of an IETF Internet-Draft or RFC and any statement made within the context "
    "of an IETF activity is considered an \"IETF Contribution\". Such statements include "
    "oral statements in IETF sessions, as well as written and electronic communications "
    "made at any time or place, which are addressed to";

// Length of the plaintext message (excluding the null terminator)
unsigned int message_len = sizeof(message_1) - 1;

// Buffer to store the encrypted message (same size as plaintext)
unsigned char encrypted_message[sizeof(message_1) - 1];

// Global index used when writing encrypted bytes (for hexdump / output)
unsigned int encrypted_index = 0;

// keystream
unsigned char keystream[sizeof(message_1) - 1];

// block states
uint32_t blocks[((sizeof(message_1) - 1 + 63) / 64) * 16];


// -----------------------------
// Test Vector #1 plaintext
// -----------------------------

// Plaintext message to be encrypted (RFC test vector: 64 bytes = 0)
unsigned char message_2[64] = {0};

// Length of the plaintext
unsigned int message_len_2 = sizeof(message_2);

// Buffer to store encrypted message
unsigned char encrypted_message_2[sizeof(message_2)];

// keystream
unsigned char keystream_2[sizeof(message_2)];

// block states (16 words por bloque)
uint32_t blocks_2[((sizeof(message_2) + 63) / 64) * 16];


// ------------------------------------------------------------
// External assembly functions
// ------------------------------------------------------------


// Extern function from your assembly
extern void quarter_round_c(uint32_t* a, uint32_t* b, uint32_t* c, uint32_t* d);

// Encrypts or decrypts a message using the ChaCha20 stream cipher.
// Since ChaCha20 is a stream cipher, the same function performs
// both encryption and decryption by XORing the plaintext/ciphertext
// with the generated keystream.
extern void chacha20_encrypt(
    uint32_t *key,
    uint32_t *counter,
    uint32_t *nonce,
    unsigned char *plaintext,
    unsigned int length
);

// ------------------------------------------------------------
// C functions
// ------------------------------------------------------------

// Simple implementation of basic functions since we're in bare-metal environment
void print_char(char c) {
    // In a real bare-metal environment, this would write to UART
    // For now, this is just a placeholder
    volatile char *uart = (volatile char*)0x10000000;
    *uart = c;
}

// Prints a null-terminated string character by character
// using the low-level print_char function.
void print_string(const char* str) {
    while (*str) {
        print_char(*str++);
    }
}

// Prints a single byte in hexadecimal format (two hex digits).
// Used for displaying ciphertext and keystream values.
void print_hex_byte(unsigned char b) {
    char hex[] = "0123456789abcdef";

    // Print high nibble
    print_char(hex[(b >> 4) & 0xF]);

    // Print low nibble
    print_char(hex[b & 0xF]);
}

// Prints a 32-bit unsigned integer in hexadecimal format (8 hex digits).
// Uses print_char to output each hexadecimal digit.
void print_hex_uint32(uint32_t x) {
    char hex[] = "0123456789abcdef";
    for (int i = 7; i >= 0; i--) {
        print_char(hex[(x >> (i*4)) & 0xF]);
    }
}

// ------------------------------------------------------------
// C function used by ASM code
// ------------------------------------------------------------

// Prints a block of bytes in hexadecimal format with ASCII representation.
// Bytes are printed in rows of 16, similar to a hex dump. Each byte is also
// stored in the global encrypted_message buffer.
void print_block(unsigned char *block, unsigned int length) {

    // Buffer to store ASCII representation of the current 16-byte line
    static char ascii[16];

    // Iterate through each byte of the block
    for (unsigned int i = 0; i < length; i++) {

        // Start a new line every 16 bytes
        if (encrypted_index % 16 == 0) {

            // If this is not the first line, print the ASCII column
            if (encrypted_index != 0) {
                print_string(" ");

                // Print ASCII characters for the previous 16 bytes
                for (int j = 0; j < 16; j++) {
                    print_char(ascii[j]);
                }

                // Move to next line
                print_string("\n");
            }
        }

        // Get current byte
        unsigned char b = block[i];

        // Store byte in the encrypted message buffer
        encrypted_message[encrypted_index] = b;

        // Print byte in hexadecimal format
        print_hex_byte(b);
        print_char(' ');

        // Save printable ASCII characters, otherwise replace with '.'
        if (b >= 32 && b <= 126)
            ascii[encrypted_index % 16] = b;
        else
            ascii[encrypted_index % 16] = '.';

        // Increment global byte index
        encrypted_index++;
    }

    int remaining = encrypted_index % 16;

    // Only print ASCII if the line is incomplete
    if (remaining != 0) {

        for (int i = remaining; i < 16; i++) {
            print_string("   ");
        }

        print_string(" ");

        for (int i = 0; i < remaining; i++) {
            print_char(ascii[i]);
        }

        print_string("\n");
    }
}

// Saves a serialized 64-byte ChaCha20 block into the global keystream buffer.
// The block is stored starting at the current encrypted_index position.
void save_serialized(unsigned char *block)
{
    for (int i = 0; i < 64; i++)
    {
        keystream[encrypted_index + i] = block[i];
    }
}


// Saves the current ChaCha20 state (16 uint32 words) into the blocks buffer.
// The position is determined by the current block index derived from encrypted_index.
void save_state(uint32_t *state)
{
    unsigned int block = encrypted_index / 64;

    for (int i = 0; i < 16; i++)
    {
        blocks[block * 16 + i] = state[i];
    }
}


// Prints the internal ChaCha20 state blocks used during encryption.
// Each block consists of 16 uint32 values (512 bits) displayed in hexadecimal format.
void print_blocks(int message_len, uint32_t *blocks)
{
    unsigned int num_blocks = (message_len + 63) / 64;

    for (unsigned int b = 0; b < num_blocks; b++)
    {
        for (int i = 0; i < 16; i++)
        {
            print_hex_uint32(blocks[b * 16 + i]);

            if ((i % 4) != 3)
                print_string("  ");
            else
                print_string("\n");
        }

        print_string("\n");
    }
}


// Prints the generated keystream in hexadecimal byte format.
// Bytes are separated by ':' and grouped in lines of 16 bytes.
void print_keystream(int message_len, unsigned char *keystream)
{
    for (unsigned int i = 0; i < message_len; i++)
    {
        print_hex_byte(keystream[i]);

        if (i != message_len - 1)
            print_char(':');

        if ((i + 1) % 16 == 0)
            print_string("\n");
    }
}

// ------------------------------------------------------------
// Main program
// ------------------------------------------------------------

void main() {

    // -----------------------------
    // Test Quarter Round Function (RFC Test Vector)
    // -----------------------------
    print_string("// -----------------------------\n");
    print_string("// Test Quarter Round Function (RFC Test Vector)\n");
    print_string("// -----------------------------\n");

    uint32_t a = 0x11111111;
    uint32_t b = 0x01020304;
    uint32_t c = 0x9b8d6f43;
    uint32_t d = 0x01234567;

    // Imprimir valores originales
    print_string("// Original Vector values:\n");
    print_hex_uint32(a); // 0x11111111
    print_char('\n');
    print_hex_uint32(b); // 0x01020304
    print_char('\n');
    print_hex_uint32(c); // 0x9b8d6f43
    print_char('\n');
    print_hex_uint32(d); // 0x01234567
    print_string("\n\n");

    // Call the quarter round function implemented in assembly
    quarter_round_c(&a, &b, &c, &d);

    // Print the results after the quarter round operation
    print_string("// Quarter Round result:\n");
    print_hex_uint32(a); // 0xea2a92f4
    print_char('\n');
    print_hex_uint32(b); // 0xcb1cf8ce
    print_char('\n');
    print_hex_uint32(c); // 0x4581472e
    print_char('\n');
    print_hex_uint32(d); // 0x5881c4bb
    print_string("\n\n");


    // -----------------------------
    // Test ChaCha20 Encryption (RFC 8439 Appendix A.2 - Vector #1)
    // -----------------------------
    print_string("// -----------------------------\n");
    print_string("// Test ChaCha20 Encryption (RFC 8439 Appendix A.2 - Vector #1)\n");
    print_string("// -----------------------------\n");


    encrypted_index = 0;

    for (int i = 0; i < 8; i++)
        key[i] = 0;

    for (int i = 0; i < 3; i++)
        nonce[i] = 0;

    counter = 0;

    unsigned int len = 64;

    print_string("\n\n");
    // Print original plaintext message
    print_string("// Original message:\n");
    print_string((char*)message_2);
    print_string("\n\n");


    // Encrypt the message using ChaCha20
    print_string("// Encrypting message...\n");
    chacha20_encrypt(key, &counter, nonce, message_2, len);

    // ---- DEBUG OUTPUT ---- 
    print_string("\nGenerated ChaCha20 blocks:\n"); 
    print_blocks(len, blocks_2); 
    print_string("\nGenerated keystream:\n"); 
    print_keystream(len, keystream_2);
    print_string("\n\n");
    
    
    // Encrypt the message using ChaCha20
    print_string("Vector #1 test completed.\n");
        print_string("\n");



    // -----------------------------
    // Test ChaCha20 Encryption (RFC 8439 Appendix A.2 - Vector #2)
    // -----------------------------
    print_string("// -----------------------------\n");
    print_string("// Test ChaCha20 Encryption (RFC 8439 Appendix A.2 - Vector #2)\n");
    print_string("// -----------------------------\n");

    // Key
    key[0] = 0x00000000;
    key[1] = 0x00000000;
    key[2] = 0x00000000;
    key[3] = 0x00000000;
    key[4] = 0x00000000;
    key[5] = 0x00000000;
    key[6] = 0x00000000;
    key[7] = 0x01000000;

    // Nonce
    nonce[0] = 0x00000000;
    nonce[1] = 0x00000000;
    nonce[2] = 0x02000000;

    // Reset index used for storing encrypted bytes
    encrypted_index = 0;

    // Counter
    counter = 1;

    len = 0;

    while (message_1[len] != '\0') {
        len++;
    }

    print_string("\n\n");
    // Print original plaintext message
    print_string("// Original message:\n");
    print_string((char*)message_1);
    print_string("\n\n");


    // Encrypt the message using ChaCha20
    print_string("// Encrypting message...\n");
    chacha20_encrypt(key, &counter, nonce, message_1, len);

    // ---- DEBUG OUTPUT ---- 
    print_string("\nGenerated ChaCha20 blocks:\n"); 
    print_blocks(len, blocks); 
    print_string("\nGenerated keystream:\n"); 
    print_keystream(len, keystream);
    print_string("\n\n");


    // Decrypt the message
    print_string("// Decrypting message...\n");

    // Reset counter to initial value for correct decryption
    counter = 1;

    // Reset index used for storing encrypted bytes
    encrypted_index = 0;

    // Decrypt by encrypting the ciphertext again with the same key and nonce
    chacha20_encrypt(key, &counter, nonce, encrypted_message, len);

    // ---- DEBUG OUTPUT ---- 
    print_string("\nGenerated ChaCha20 blocks:\n"); 
    print_blocks(len, blocks); 
    print_string("\nGenerated keystream:\n"); 
    print_keystream(len, keystream);
    print_string("\n\n");

    print_string("// Tests completed.\n");
    
    
    // Infinite loop to keep program running
    while (1) {
        __asm__ volatile ("nop");
    }
}